import Head from 'next/head'
import styles from '../styles/home1.module.css'
import Image from 'next/image'
import Popular from '../components/popular';
import Script from 'next/script';
import Link from 'next/link';
import Latest from '../components/latest';
import Footer from '../components/footer';
// import styles from '../styles/Home.module.css'

export default function Home() {
  const img = "/img6.jpg";
  return (
    <>
    <style jsx>
          {`
              .part1{
                background-image: url(${img});
                background-size: cover;
                padding-top:0px;
                margin-top:50px;
                box-shadow: 0 2px 2px -2px rgba(0,0,0,.4);
              }
              `}
        </style>
              
      <Head>
        <title>Tech Fallacy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>
        <Script src="https://kit.fontawesome.com/004c7e6d5b.js" crossOrigin="anonymous"></Script>

      <div className="part1">
      
      <main className={styles.main}>
        <h1 className={styles.title1}>
          <span className={styles.myspan}>TechFallacy</span>
        </h1>
      
        <p className={styles.description}>
          Here you get all mobile phones and electronics accessories reviews and found links of them at best price
        </p>
      
        {/* <a><button className={styles.button}>Lets Start</button></a> */}
        <Link href='/'>
                    <a className="mr-4 ml-6 whitespace-nowrap inline-flex items-center justify-center px-3 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-indigo-600 hover:bg-indigo-700"> Sign up </a>
        </Link>
      
      </main>  
      </div>

      <Popular/>
      <Latest/>
      <Footer/>
      
    </>
  )
}
